import {
  Client,
  StampStockItem,
  StampMovement,
  StampAdjustment,
  TaxCase,
  ServiceOrder,
  Receipt,
  Expense,
  RecurringExpense,
  UtilityBill,
  DailyClosing,
  SystemUser,
  AuditLog,
  OfficeTask,
  LedgerTransaction,
  BusinessSettings
} from '../types';

export const initialBusinessSettings: BusinessSettings = {
  businessName: 'CH Composing E-Stamp & Tax Advisor',
  legalName: 'CH Legal Composing & Tax Advisory Consultancy',
  address: 'Chamber No. 121, Kachahri Sahiwal, Punjab, Pakistan',
  phone: '+92 300 1234567',
  whatsapp: '+92 300 1234567',
  email: 'info@chcomposing.pk',
  ntnNumber: '1234567-8',
  chamberNumber: 'Chamber No. 121',
  receiptFooter: 'Thank you for your business! Generated by CH Admin Portal.'
};

export const initialClients: Client[] = [
  {
    id: 'c-1',
    name: 'Muhammad Ali Khan',
    cnic: '35202-1234567-1',
    ntn: '1234567-8',
    mobile: '0300-1112233',
    email: 'ali.traders@gmail.com',
    businessName: 'Ali Traders',
    businessType: 'General Trading' as any,
    address: 'Chamber No. 121, Sahiwal / Main Bazar',
    taxStatus: 'Active',
    memberSince: '12 Jan 2024',
    outstanding: 25000,
    status: 'Active',
    totalBilling: 125000,
    paidAmount: 100000,
    lifetimeRevenue: 100000,
    lastService: '22-09-2025',
    documents: [
      { id: 'd-1', name: 'CNIC_Muhammad_Ali.pdf', type: 'PDF', uploadDate: '12 Jan 2024', size: '1.2 MB', category: 'CNIC' },
      { id: 'd-2', name: 'NTN_Certificate.pdf', type: 'PDF', uploadDate: '15 Jan 2024', size: '850 KB', category: 'NTN' },
      { id: 'd-3', name: 'Bank_Statement_2024.pdf', type: 'PDF', uploadDate: '10 Aug 2025', size: '3.4 MB', category: 'Bank Statement' }
    ],
    notes: 'Key client for annual income tax returns and business registration affidavits.'
  },
  {
    id: 'c-2',
    name: 'Zara Enterprises',
    cnic: '35202-7654321-0',
    ntn: '7654321-0',
    mobile: '0301-2223344',
    email: 'zara@enterprises.pk',
    businessName: 'Zara Enterprises',
    businessType: 'Private Limited',
    address: 'Circular Road, Sahiwal',
    taxStatus: 'Active',
    memberSince: '05 Feb 2023',
    outstanding: 0,
    status: 'Active',
    totalBilling: 180000,
    paidAmount: 180000,
    lifetimeRevenue: 180000,
    lastService: '21-09-2025',
    documents: [
      { id: 'd-4', name: 'Form_29_Zara_Enterprises.pdf', type: 'PDF', uploadDate: '05 Feb 2023', size: '2.1 MB', category: 'Challan' }
    ]
  },
  {
    id: 'c-3',
    name: 'Asad Khan',
    cnic: '35202-1111111-1',
    ntn: '2345678-1',
    mobile: '0302-3334455',
    email: 'asad@khanco.pk',
    businessName: 'Khan & Co.',
    businessType: 'Sole Proprietorship',
    address: 'High Court Road, Sahiwal',
    taxStatus: 'Active',
    memberSince: '18 Mar 2023',
    outstanding: 12500,
    status: 'Active',
    totalBilling: 95000,
    paidAmount: 82500,
    lifetimeRevenue: 82500,
    lastService: '20-09-2025',
    documents: []
  },
  {
    id: 'c-4',
    name: 'Bilal Ahmed',
    cnic: '35202-2222222-2',
    ntn: '3456789-2',
    mobile: '0303-4445566',
    email: 'bilal@baindustries.com',
    businessName: 'BA Industries',
    businessType: 'Partnership',
    address: 'Industrial Area, Sahiwal',
    taxStatus: 'Active',
    memberSince: '20 Apr 2022',
    outstanding: 48000,
    status: 'Outstanding',
    totalBilling: 220000,
    paidAmount: 172000,
    lifetimeRevenue: 172000,
    lastService: '19-09-2025',
    documents: []
  },
  {
    id: 'c-5',
    name: 'Ahsan Traders',
    cnic: '35202-3333333-3',
    ntn: '4567890-3',
    mobile: '0304-5556677',
    email: 'ahsan@traders.com',
    businessName: 'Ahsan Traders',
    businessType: 'Sole Proprietorship',
    address: 'Grain Market, Sahiwal',
    taxStatus: 'Active',
    memberSince: '11 Jun 2023',
    outstanding: 0,
    status: 'Active',
    totalBilling: 65000,
    paidAmount: 65000,
    lifetimeRevenue: 65000,
    lastService: '18-09-2025',
    documents: []
  },
  {
    id: 'c-6',
    name: 'Saima Bibi',
    cnic: '35202-4444444-4',
    ntn: '5678901-4',
    mobile: '0305-6667788',
    email: 'saima@cosmetics.pk',
    businessName: 'Saima Cosmetics',
    businessType: 'Individual',
    address: 'Liaqat Bazar, Sahiwal',
    taxStatus: 'Active',
    memberSince: '14 Jan 2024',
    outstanding: 8200,
    status: 'Active',
    totalBilling: 40000,
    paidAmount: 31800,
    lifetimeRevenue: 31800,
    lastService: '17-09-2025',
    documents: []
  },
  {
    id: 'c-7',
    name: 'Raza Enterprises',
    cnic: '35202-5555555-5',
    ntn: '6789012-5',
    mobile: '0306-7778899',
    email: 'raza@enterprises.pk',
    businessName: 'Raza Enterprises',
    businessType: 'AOP',
    address: 'Pakpattan Chowk, Sahiwal',
    taxStatus: 'Filer',
    memberSince: '09 Sep 2023',
    outstanding: 35000,
    status: 'Outstanding',
    totalBilling: 110000,
    paidAmount: 75000,
    lifetimeRevenue: 75000,
    lastService: '16-09-2025',
    documents: []
  },
  {
    id: 'c-8',
    name: 'Nadeem & Sons',
    cnic: '35202-6666666-6',
    ntn: '7890123-6',
    mobile: '0307-8889900',
    email: 'nadeem@sons.pk',
    businessName: 'Nadeem & Sons',
    businessType: 'Partnership',
    address: 'Railway Road, Sahiwal',
    taxStatus: 'Non-Filer',
    memberSince: '15 Oct 2023',
    outstanding: 0,
    status: 'Active',
    totalBilling: 55000,
    paidAmount: 55000,
    lifetimeRevenue: 55000,
    lastService: '15-09-2025',
    documents: []
  },
  {
    id: 'c-9',
    name: 'Khan Associates',
    cnic: '35202-7777777-7',
    ntn: '8901234-7',
    mobile: '0308-9990011',
    email: 'info@khanassociates.pk',
    businessName: 'Khan Associates',
    businessType: 'Private Limited',
    address: 'Civil Lines, Sahiwal',
    taxStatus: 'Active',
    memberSince: '28 Nov 2022',
    outstanding: 18500,
    status: 'Outstanding',
    totalBilling: 145000,
    paidAmount: 126500,
    lifetimeRevenue: 126500,
    lastService: '14-09-2025',
    documents: []
  },
  {
    id: 'c-10',
    name: 'Tariq Mehmood',
    cnic: '35202-8888888-8',
    ntn: '9012345-8',
    mobile: '0309-1110022',
    email: 'tariq@tmconstruction.pk',
    businessName: 'TM Construction',
    businessType: 'Sole Proprietorship',
    address: 'Depalpur Bazar, Sahiwal',
    taxStatus: 'Filer',
    memberSince: '02 Dec 2023',
    outstanding: 0,
    status: 'Active',
    totalBilling: 80000,
    paidAmount: 80000,
    lifetimeRevenue: 80000,
    lastService: '12-09-2025',
    documents: []
  }
];

export const initialStampStock: StampStockItem[] = [
  { denomination: 50, openingStock: 200, purchased: 500, sold: 620, remaining: 80, purchasePrice: 42, salePrice: 50, stockValue: 4000, minimumLevel: 100, status: 'Low' },
  { denomination: 100, openingStock: 150, purchased: 400, sold: 320, remaining: 230, purchasePrice: 85, salePrice: 100, stockValue: 23000, minimumLevel: 100, status: 'OK' },
  { denomination: 500, openingStock: 80, purchased: 200, sold: 150, remaining: 130, purchasePrice: 420, salePrice: 500, stockValue: 65000, minimumLevel: 50, status: 'OK' },
  { denomination: 1000, openingStock: 50, purchased: 120, sold: 90, remaining: 80, purchasePrice: 850, salePrice: 1000, stockValue: 80000, minimumLevel: 100, status: 'OK' },
  { denomination: 5000, openingStock: 20, purchased: 60, sold: 45, remaining: 35, purchasePrice: 4200, salePrice: 5000, stockValue: 175000, minimumLevel: 50, status: 'Low' }
];

export const initialStampMovements: StampMovement[] = [
  { id: 'sm-1', dateTime: '22-09-2025 11:45 AM', type: 'Sale', denomination: 100, qty: -10, balance: 230, clientOrSupplier: 'Asad Khan', amount: 1000, user: 'Usama' },
  { id: 'sm-2', dateTime: '22-09-2025 10:20 AM', type: 'Purchase', denomination: 500, qty: 50, balance: 130, clientOrSupplier: 'State Bank', amount: 21000, user: 'Staff' },
  { id: 'sm-3', dateTime: '21-09-2025 03:10 PM', type: 'Adjustment', denomination: 50, qty: -20, balance: 80, clientOrSupplier: 'Internal Audit', amount: 1000, user: 'Usama', notes: 'Damaged stamps (torn edges)' },
  { id: 'sm-4', dateTime: '22-09-2025 12:45 PM', type: 'Sale', denomination: 1000, qty: -5, balance: 80, clientOrSupplier: 'Hassan & Co.', amount: 5000, user: 'Admin' },
  { id: 'sm-5', dateTime: '19-09-2025 09:15 AM', type: 'Purchase', denomination: 100, qty: 100, balance: 240, clientOrSupplier: 'State Bank', amount: 8500, user: 'Usama' }
];

export const initialStampAdjustments: StampAdjustment[] = [
  { id: 'sa-1', dateTime: '21-09-2025 03:10 PM', denomination: 50, previousStock: 100, adjustedStock: 80, difference: -20, reason: 'Damaged stamps (torn edges)', adjustedBy: 'Usama' },
  { id: 'sa-2', dateTime: '17-09-2025 11:25 AM', denomination: 1000, previousStock: 85, adjustedStock: 80, difference: -5, reason: 'Physical count adjustment', adjustedBy: 'Admin' },
  { id: 'sa-3', dateTime: '12-09-2025 09:40 AM', denomination: 500, previousStock: 120, adjustedStock: 130, difference: 10, reason: 'Excess found in physical count', adjustedBy: 'Usama' }
];

export const initialTransactions: LedgerTransaction[] = [
  { id: 'tx-1', dateTime: '22-09-2025 11:45 AM', type: 'IN', description: 'Tax Return Fee', clientOrPayee: 'Muhammad Ali', serviceOrCategory: 'Income Tax Return', account: 'cash', amount: 5000, staff: 'Usama', status: 'Completed', receiptNo: 'REC-2025-000125' },
  { id: 'tx-2', dateTime: '22-09-2025 11:20 AM', type: 'IN', description: 'Stamp Sale', clientOrPayee: 'Cash Sale', serviceOrCategory: 'Stamp Paper', account: 'cash', amount: 2800, staff: 'Staff', status: 'Completed' },
  { id: 'tx-3', dateTime: '22-09-2025 10:55 AM', type: 'OUT', description: 'Office Tea', clientOrPayee: 'Office Expense', serviceOrCategory: 'Refreshment', account: 'cash', amount: 300, staff: 'Usama', status: 'Completed' },
  { id: 'tx-4', dateTime: '22-09-2025 10:30 AM', type: 'IN', description: 'Composing Charges', clientOrPayee: 'Ahsan Traders', serviceOrCategory: 'Composing', account: 'bank', amount: 12000, staff: 'Staff', status: 'Completed' },
  { id: 'tx-5', dateTime: '22-09-2025 09:50 AM', type: 'OUT', description: 'Internet Bill', clientOrPayee: 'Jazz Telecom', serviceOrCategory: 'Utilities', account: 'jazzcash', amount: 4500, staff: 'Usama', status: 'Completed' },
  { id: 'tx-6', dateTime: '22-09-2025 09:10 AM', type: 'IN', description: 'Stamp Purchase (Client)', clientOrPayee: 'Zara Enterprises', serviceOrCategory: 'Stamp Purchase', account: 'cash', amount: 3200, staff: 'Staff', status: 'Completed' },
  { id: 'tx-7', dateTime: '22-09-2025 09:00 AM', type: 'OUT', description: 'Stationery Purchase', clientOrPayee: 'Al-Faisal Stationers', serviceOrCategory: 'Stationery', account: 'cash', amount: 1200, staff: 'Usama', status: 'Completed' },
  { id: 'tx-8', dateTime: '22-09-2025 08:45 AM', type: 'IN', description: 'NTN Registration Fee', clientOrPayee: 'Bilal Ahmed', serviceOrCategory: 'NTN Registration', account: 'bank', amount: 8500, staff: 'Staff', status: 'Completed' }
];

export const initialTaxCases: TaxCase[] = [
  {
    id: 'tc-1',
    clientName: 'Muhammad Ali',
    clientId: 'c-1',
    clientType: 'Individual Client',
    taxYear: '2024 - 2025',
    returnType: 'Income Tax Return',
    assignedStaff: 'Usama (Admin)',
    amountFee: 12500,
    amountPaid: 5000,
    outstanding: 7500,
    dueDate: '25 September 2025',
    status: 'Documents Required',
    notes: 'Client to provide salary certificate, bank statements and investment details.',
    requiredDocuments: [
      { name: 'CNIC Copy', checked: true, description: 'Required for all returns' },
      { name: 'Salary Certificate', checked: false, description: 'For salaried individuals' },
      { name: 'Bank Statements (Last 6 Months)', checked: true, description: 'Required for ITR' },
      { name: 'Sales Invoices', checked: false, description: 'For sales tax returns' },
      { name: 'Purchase Invoices', checked: false, description: 'For claim of input tax' },
      { name: 'Investment Details', checked: false, description: 'For capital gains / wealth statement' }
    ]
  },
  {
    id: 'tc-2',
    clientName: 'Zara Enterprises',
    clientId: 'c-2',
    clientType: 'Corporate Filer',
    taxYear: 'Aug 2025',
    returnType: 'Sales Tax Return',
    assignedStaff: 'Hamza',
    amountFee: 8000,
    amountPaid: 8000,
    outstanding: 0,
    dueDate: '28 Sep 2025',
    status: 'Documents Required',
    notes: 'Awaiting export invoices and customs annexures.',
    requiredDocuments: [
      { name: 'CNIC Copy', checked: true },
      { name: 'Sales Invoices', checked: false },
      { name: 'Purchase Invoices', checked: true }
    ]
  },
  {
    id: 'tc-3',
    clientName: 'Ahsan Traders',
    clientId: 'c-5',
    clientType: 'Sole Proprietorship',
    taxYear: '2024 - 2025',
    returnType: 'Income Tax Return',
    assignedStaff: 'Usama',
    amountFee: 25000,
    amountPaid: 25000,
    outstanding: 0,
    dueDate: '30 Sep 2025',
    status: 'In Progress',
    notes: 'Calculating business depreciation and turnover tax.',
    requiredDocuments: [
      { name: 'CNIC Copy', checked: true },
      { name: 'Bank Statements (Last 6 Months)', checked: true }
    ]
  },
  {
    id: 'tc-4',
    clientName: 'Bilal Ahmed',
    clientId: 'c-4',
    clientType: 'AOP',
    taxYear: 'Aug 2025',
    returnType: 'NTN Registration',
    assignedStaff: 'Ayesha',
    amountFee: 3000,
    amountPaid: 3000,
    outstanding: 0,
    dueDate: '02 Oct 2025',
    status: 'In Progress',
    notes: 'Submitting biometric verification slip at RTO Sahiwal.',
    requiredDocuments: [{ name: 'CNIC Copy', checked: true }]
  },
  {
    id: 'tc-5',
    clientName: 'Asad Khan',
    clientId: 'c-3',
    clientType: 'Individual',
    taxYear: '2024 - 2025',
    returnType: 'Income Tax Return',
    assignedStaff: 'Usama',
    amountFee: 18500,
    amountPaid: 18500,
    outstanding: 0,
    dueDate: '25 Sep 2025',
    status: 'Ready to File',
    notes: 'Draft finalized and vetted. Ready for IRIS upload.',
    requiredDocuments: [{ name: 'CNIC Copy', checked: true }, { name: 'Salary Certificate', checked: true }]
  },
  {
    id: 'tc-6',
    clientName: 'Faiza Builders (Pvt) Ltd',
    clientId: 'c-9',
    clientType: 'Pvt Ltd',
    taxYear: 'Aug 2025',
    returnType: 'Sales Tax Return',
    assignedStaff: 'Hamza',
    amountFee: 32000,
    amountPaid: 32000,
    outstanding: 0,
    dueDate: '27 Sep 2025',
    status: 'Ready to File',
    notes: 'Annexure C and F cleared without discrepancy.',
    requiredDocuments: [{ name: 'Sales Invoices', checked: true }]
  },
  {
    id: 'tc-7',
    clientName: 'Hassan & Co.',
    clientId: 'c-3',
    clientType: 'Partnership',
    taxYear: '2024 - 2025',
    returnType: 'Income Tax Return',
    assignedStaff: 'Usama',
    amountFee: 21000,
    amountPaid: 21000,
    outstanding: 0,
    dueDate: '18 Sep 2025',
    filedDate: '18 Sep 2025',
    status: 'Submitted',
    notes: 'Acknowledgment slip generated from FBR IRIS portal.',
    requiredDocuments: [{ name: 'CNIC Copy', checked: true }]
  },
  {
    id: 'tc-8',
    clientName: 'Nadeem Plastic Works',
    clientId: 'c-8',
    clientType: 'Sole Proprietor',
    taxYear: 'Aug 2025',
    returnType: 'Sales Tax Return',
    assignedStaff: 'Ayesha',
    amountFee: 15000,
    amountPaid: 15000,
    outstanding: 0,
    dueDate: '16 Sep 2025',
    filedDate: '16 Sep 2025',
    status: 'Submitted',
    notes: 'Tax paid at National Bank Sahiwal.',
    requiredDocuments: [{ name: 'Bank Statements', checked: true }]
  },
  {
    id: 'tc-9',
    clientName: 'Ali Traders',
    clientId: 'c-1',
    clientType: 'Commercial',
    taxYear: '2024 - 2025',
    returnType: 'Income Tax Return',
    assignedStaff: 'Usama',
    amountFee: 10000,
    amountPaid: 10000,
    outstanding: 0,
    dueDate: '05 Sep 2025',
    filedDate: '05 Sep 2025',
    status: 'Completed',
    notes: 'Assessment order downloaded and handed over to client.',
    requiredDocuments: [{ name: 'CNIC Copy', checked: true }]
  },
  {
    id: 'tc-10',
    clientName: 'Punjab Textiles',
    clientId: 'c-4',
    clientType: 'Industrial',
    taxYear: 'Jul 2025',
    returnType: 'Sales Tax Return',
    assignedStaff: 'Hamza',
    amountFee: 42000,
    amountPaid: 42000,
    outstanding: 0,
    dueDate: '02 Sep 2025',
    filedDate: '02 Sep 2025',
    status: 'Completed',
    notes: 'Refund claim processed.',
    requiredDocuments: []
  }
];

export const initialServiceOrders: ServiceOrder[] = [
  { id: 'so-1', orderNo: '001', dateTime: '22-09-2025 11:45 AM', serviceName: 'Composing', customer: 'Muhammad Ali', fileReference: 'CMP-2025-001', pages: 12, turnaroundTime: '2 Hours', amount: 1500, payment: 'Paid', staff: 'Usama', status: 'In Progress', contact: '0300-1234567', specialInstructions: 'Format in legal style, add client logo and prepare final PDF.' },
  { id: 'so-2', orderNo: '002', dateTime: '22-09-2025 11:20 AM', serviceName: 'Affidavit', customer: 'Sara Khan', fileReference: 'AFF-2025-072', pages: 3, turnaroundTime: '1 Hour', amount: 800, payment: 'Paid', staff: 'Asad', status: 'Completed', contact: '0301-7654321', specialInstructions: 'Affidavit regarding property declaration.' },
  { id: 'so-3', orderNo: '003', dateTime: '22-09-2025 10:55 AM', serviceName: 'Agreement', customer: 'Zara Enterprises', fileReference: 'AGR-2025-014', pages: 8, turnaroundTime: '4 Hours', amount: 2500, payment: 'Unpaid', staff: 'Bilal', status: 'Pending', contact: '0302-9988776', specialInstructions: 'Commercial partnership draft.' },
  { id: 'so-4', orderNo: '004', dateTime: '22-09-2025 10:30 AM', serviceName: 'E-Stamp', customer: 'Asif Traders', fileReference: 'EST-2025-221', pages: 2, turnaroundTime: '30 Min', amount: 400, payment: 'Paid', staff: 'Usama', status: 'Completed', contact: '0303-1122334', specialInstructions: 'Generate 32-A challan for property sale.' },
  { id: 'so-5', orderNo: '005', dateTime: '22-09-2025 10:05 AM', serviceName: 'Printing', customer: 'Ali Raza', fileReference: 'PRT-2025-109', pages: 25, turnaroundTime: '1 Hour', amount: 1250, payment: 'Paid', staff: 'Ahsan', status: 'In Progress', contact: '0304-4455667', specialInstructions: 'Color prints on 80gsm paper.' },
  { id: 'so-6', orderNo: '006', dateTime: '22-09-2025 09:40 AM', serviceName: 'Photocopy', customer: 'Commission Agent', fileReference: 'PC-2025-076', pages: 40, turnaroundTime: '30 Min', amount: 600, payment: 'Paid', staff: 'Asad', status: 'Completed', contact: '0305-6677889' },
  { id: 'so-7', orderNo: '007', dateTime: '22-09-2025 09:15 AM', serviceName: 'NTN Registration', customer: 'Bilal Ahmed', fileReference: 'NTN-2025-018', pages: 5, turnaroundTime: '2 Hours', amount: 1800, payment: 'Unpaid', staff: 'Usama', status: 'Pending', contact: '0303-4445566' },
  { id: 'so-8', orderNo: '008', dateTime: '22-09-2025 08:50 AM', serviceName: 'Return Filing', customer: 'Hassan & Co.', fileReference: 'RET-2025-091', pages: 18, turnaroundTime: '6 Hours', amount: 3000, payment: 'Paid', staff: 'Bilal', status: 'In Progress', contact: '0306-8899001' },
  { id: 'so-9', orderNo: '009', dateTime: '22-09-2025 08:20 AM', serviceName: 'Stamp Paper', customer: 'Farhan Malik', fileReference: 'SP-2025-063', pages: 1, turnaroundTime: '30 Min', amount: 300, payment: 'Paid', staff: 'Ahsan', status: 'Delivered', contact: '0307-1239874' },
  { id: 'so-10', orderNo: '010', dateTime: '22-09-2025 08:10 AM', serviceName: 'Other (Letter)', customer: 'Walk-in Client', fileReference: 'OTH-2025-045', pages: 4, turnaroundTime: '1 Hour', amount: 500, payment: 'Paid', staff: 'Usama', status: 'Completed', contact: '0308-5544332' }
];

export const initialReceipts: Receipt[] = [
  { id: 'rec-1', receiptNo: 'REC-2025-000125', dateTime: '22-09-2025 11:45 AM', clientName: 'Muhammad Ali', service: 'Income Tax Return', amount: 5000, paidAmount: 5000, balance: 0, paymentMethod: 'Cash', remarks: 'Income Tax Return for Tax Year 2025', status: 'PAID', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-2', receiptNo: 'REC-2025-000124', dateTime: '22-09-2025 10:32 AM', clientName: 'Zara Enterprises', service: 'Sales Tax Return', amount: 12000, paidAmount: 6000, balance: 6000, paymentMethod: 'Bank Transfer', remarks: 'Monthly filing charges', status: 'PARTIAL', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-3', receiptNo: 'REC-2025-000123', dateTime: '21-09-2025 04:15 PM', clientName: 'Ahsan Traders', service: 'Composing', amount: 2500, paidAmount: 2500, balance: 0, paymentMethod: 'Cash', remarks: 'Commercial Agreement Typing', status: 'PAID', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-4', receiptNo: 'REC-2025-000122', dateTime: '21-09-2025 12:08 PM', clientName: 'Bilal Ahmed', service: 'NTN Registration', amount: 8000, paidAmount: 0, balance: 8000, paymentMethod: 'Cheque', remarks: 'Cheque returned by bank', status: 'CANCELLED', authorizedBy: 'CH Composing & Tax Advisor', cancellationReason: 'Client cancelled request' },
  { id: 'rec-5', receiptNo: 'REC-2025-000121', dateTime: '20-09-2025 03:40 PM', clientName: 'Asad Khan', service: 'Stamp Purchase', amount: 5000, paidAmount: 5000, balance: 0, paymentMethod: 'Cash', remarks: '5x Rs. 1000 Stamp Papers', status: 'PAID', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-6', receiptNo: 'REC-2025-000120', dateTime: '20-09-2025 11:20 AM', clientName: 'Hassan & Co.', service: 'Tax Consultancy', amount: 18000, paidAmount: 10000, balance: 8000, paymentMethod: 'Bank Transfer', remarks: 'Advance against corporate advisory', status: 'PARTIAL', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-7', receiptNo: 'REC-2025-000119', dateTime: '19-09-2025 02:15 PM', clientName: 'Faizan Traders', service: 'File Preparation', amount: 3000, paidAmount: 3000, balance: 0, paymentMethod: 'Cash', remarks: 'FBR File formatting', status: 'PAID', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-8', receiptNo: 'REC-2025-000118', dateTime: '18-09-2025 04:05 PM', clientName: 'Sana Marketing', service: 'Sales Tax Return', amount: 7500, paidAmount: 7500, balance: 0, paymentMethod: 'JazzCash', remarks: 'Sales Tax August filing', status: 'PAID', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-9', receiptNo: 'REC-2025-000117', dateTime: '18-09-2025 11:30 AM', clientName: 'Al Rehman Co.', service: 'Composing', amount: 4000, paidAmount: 2000, balance: 2000, paymentMethod: 'Cash', remarks: 'Court Affidavit writing', status: 'PARTIAL', authorizedBy: 'CH Composing & Tax Advisor' },
  { id: 'rec-10', receiptNo: 'REC-2025-000116', dateTime: '17-09-2025 05:45 PM', clientName: 'Naseem Ullah', service: 'Income Tax Return', amount: 6000, paidAmount: 0, balance: 6000, paymentMethod: 'Cash', remarks: 'Client requested postponement', status: 'CANCELLED', authorizedBy: 'CH Composing & Tax Advisor', cancellationReason: 'Postponed by client' }
];

export const initialExpenses: Expense[] = [
  { id: 'exp-1', date: '22-09-2025', category: 'Electricity', description: 'Electricity Bill - September 2025', vendorPayee: 'LESCO', account: 'Meezan Bank', amount: 12400, staff: 'Usama', status: 'Paid' },
  { id: 'exp-2', date: '21-09-2025', category: 'Tea & Refreshment', description: 'Tea for Clients', vendorPayee: 'Chaudhry Tea Stall', account: 'Cash', amount: 850, staff: 'Ali Traders', status: 'Paid' },
  { id: 'exp-3', date: '20-09-2025', category: 'Stationery', description: 'Printer Paper & Files', vendorPayee: 'Computer Zone', account: 'Cash', amount: 2300, staff: 'Usama', status: 'Paid' },
  { id: 'exp-4', date: '19-09-2025', category: 'Transport', description: 'Fuel for Office Vehicle', vendorPayee: 'PSO', account: 'Cash', amount: 5000, staff: 'Asad Khan', status: 'Paid' },
  { id: 'exp-5', date: '18-09-2025', category: 'Internet', description: 'Monthly Internet Bill', vendorPayee: 'PTCL', account: 'Meezan Bank', amount: 8000, staff: 'Usama', status: 'Paid' },
  { id: 'exp-6', date: '17-09-2025', category: 'Maintenance', description: 'AC Servicing', vendorPayee: 'Cool Tech Services', account: 'Cash', amount: 4500, staff: 'Bilal Ahmed', status: 'Pending' },
  { id: 'exp-7', date: '16-09-2025', category: 'Stamp Purchase', description: 'E-Stamp Purchase (Bulk)', vendorPayee: 'SBP', account: 'Cash', amount: 10000, staff: 'Usama', status: 'Paid' },
  { id: 'exp-8', date: '15-09-2025', category: 'Rent', description: 'Office Rent - September 2025', vendorPayee: 'Malik Estate', account: 'Meezan Bank', amount: 80000, staff: 'Admin', status: 'Pending' },
  { id: 'exp-9', date: '14-09-2025', category: 'Government Fee', description: 'Professional Tax', vendorPayee: 'FBR', account: 'Bank Alfalah', amount: 3500, staff: 'Usama', status: 'Paid' },
  { id: 'exp-10', date: '12-09-2025', category: 'Salary', description: 'Staff Salary - September 2025', vendorPayee: 'Office Staff', account: 'Cash', amount: 60000, staff: 'Admin', status: 'Paid' }
];

export const initialRecurringExpenses: RecurringExpense[] = [
  { id: 're-1', description: 'Office Rent', amount: 80000, frequency: 'Monthly', nextDue: '01-10-2025', status: 'Active' },
  { id: 're-2', description: 'Internet (PTCL)', amount: 8000, frequency: 'Monthly', nextDue: '25-09-2025', status: 'Active' },
  { id: 're-3', description: 'Electricity (LESCO)', amount: 12000, frequency: 'Monthly', nextDue: '28-09-2025', status: 'Active' },
  { id: 're-4', description: 'Staff Salaries', amount: 60000, frequency: 'Monthly', nextDue: '01-10-2025', status: 'Active' },
  { id: 're-5', description: 'Office Maintenance', amount: 5000, frequency: 'Monthly', nextDue: '05-10-2025', status: 'Active' }
];

export const initialUtilityBills: UtilityBill[] = [
  { id: 'ub-1', vendor: 'LESCO', billType: 'Electricity', amount: 12000, dueDate: '28-09-2025', daysLeft: 6, status: 'Pending' },
  { id: 'ub-2', vendor: 'PTCL', billType: 'Internet', amount: 8000, dueDate: '25-09-2025', daysLeft: 3, status: 'Pending' },
  { id: 'ub-3', vendor: 'SNGPL', billType: 'Gas', amount: 4500, dueDate: '30-09-2025', daysLeft: 8, status: 'Pending' },
  { id: 'ub-4', vendor: 'Sahiwal Water', billType: 'Water', amount: 2800, dueDate: '30-09-2025', daysLeft: 8, status: 'Pending' },
  { id: 'ub-5', vendor: 'Municipal Committee', billType: 'Property Tax', amount: 15000, dueDate: '10-10-2025', daysLeft: 18, status: 'Pending' }
];

export const initialSystemUsers: SystemUser[] = [
  { id: 'u-1', name: 'Usama Ali', email: 'usama@ch.com', role: 'Admin', status: 'Online', lastLogin: '22-09-2025 11:45 AM', avatarInitials: 'UA', phone: '0300-1234567' },
  { id: 'u-2', name: 'Asad Khan', email: 'asad@ch.com', role: 'Tax Consultant', status: 'Online', lastLogin: '22-09-2025 10:32 AM', avatarInitials: 'AK', phone: '0302-3334455' },
  { id: 'u-3', name: 'Zara Enterprises', email: 'zara@ch.com', role: 'Stamp Vendor', status: 'Offline', lastLogin: '22-09-2025 09:15 AM', avatarInitials: 'ZE', phone: '0301-2223344' },
  { id: 'u-4', name: 'Bilal Ahmed', email: 'bilal@ch.com', role: 'Accountant', status: 'Online', lastLogin: '22-09-2025 11:20 AM', avatarInitials: 'BA', phone: '0303-4445566' },
  { id: 'u-5', name: 'Ahsan Traders', email: 'ahsan@ch.com', role: 'Staff', status: 'Offline', lastLogin: '21-09-2025 05:10 PM', avatarInitials: 'AT', phone: '0304-5556677' },
  { id: 'u-6', name: 'Faiza Noor', email: 'faiza@ch.com', role: 'Staff', status: 'Online', lastLogin: '22-09-2025 10:58 AM', avatarInitials: 'FN', phone: '0306-7788990' }
];

export const initialAuditLogs: AuditLog[] = [
  { id: 'al-1', dateTime: '22-09-2025 11:46 AM', user: 'Usama Ali', action: 'Login', module: 'System', beforePrevious: '-', afterNew: 'User logged in', ipAddress: '192.168.1.10', sessionStatus: 'Success' },
  { id: 'al-2', dateTime: '22-09-2025 11:32 AM', user: 'Asad Khan', action: 'Update', module: 'Client', beforePrevious: 'Phone: 0300-1234567', afterNew: 'Phone: 0300-7654321', ipAddress: '192.168.1.11', sessionStatus: 'Success' },
  { id: 'al-3', dateTime: '22-09-2025 11:20 AM', user: 'Bilal Ahmed', action: 'Create', module: 'Receipt', beforePrevious: '-', afterNew: 'Receipt #R-2025-000125', ipAddress: '192.168.1.14', sessionStatus: 'Success' },
  { id: 'al-4', dateTime: '22-09-2025 10:58 AM', user: 'Faiza Noor', action: 'Login', module: 'System', beforePrevious: '-', afterNew: 'User logged in', ipAddress: '192.168.1.20', sessionStatus: 'Success' },
  { id: 'al-5', dateTime: '22-09-2025 10:45 AM', user: 'Zara Enterprises', action: 'Update', module: 'Service', beforePrevious: 'Rate: 2,000', afterNew: 'Rate: 2,500', ipAddress: '192.168.1.15', sessionStatus: 'Success' },
  { id: 'al-6', dateTime: '22-09-2025 10:30 AM', user: 'Ahsan Traders', action: 'Delete', module: 'Client', beforePrevious: 'Client ID: C-0123', afterNew: 'Client deleted', ipAddress: '192.168.1.18', sessionStatus: 'Failed' }
];

export const initialTasks: OfficeTask[] = [
  { id: 't-1', title: 'Collect bank statements - Muhammad Ali', client: 'Muhammad Ali', assignedStaff: 'Hamza', dueDate: '22 Sep 2025', priority: 'High', status: 'Pending', description: 'Need original bank stamped statements for tax year 2025.' },
  { id: 't-2', title: 'Prepare ITR draft - Asad Khan', client: 'Asad Khan', assignedStaff: 'Usama', dueDate: '23 Sep 2025', priority: 'High', status: 'In Progress', description: 'Finalize wealth statement reconciliation.' },
  { id: 't-3', title: 'Verify sales invoices - Zara Enterprises', client: 'Zara Enterprises', assignedStaff: 'Ayesha', dueDate: '24 Sep 2025', priority: 'Medium', status: 'Pending', description: 'Reconcile sales tax invoices with buyer declarations.' },
  { id: 't-4', title: 'Prepare withholding statement', client: 'Hassan & Co.', assignedStaff: 'Hamza', dueDate: '26 Sep 2025', priority: 'Medium', status: 'Pending', description: 'Monthly CPR and section 149 calculation.' },
  { id: 't-5', title: 'Client follow-up - Bilal Ahmed', client: 'Bilal Ahmed', assignedStaff: 'Usama', dueDate: '27 Sep 2025', priority: 'Low', status: 'Waiting Client', description: 'Request missing electricity bill copies.' }
];

export const initialDailyClosing: DailyClosing = {
  date: '2025-09-22',
  openingBalance: 38500,
  cashIn: 42500,
  cashOut: 8200,
  expectedCash: 72800,
  actualCash: 72800,
  difference: 0,
  isClosed: false
};
